name: Deploy React Frontend

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: self-hosted # Triggers your new bare-metal worker agent
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          no-cache: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to K8s Cluster
        run: |
          # 1. Force kill the old container to completely free up physical port 8082
          kubectl scale deployment react-frontend-deployment --replicas=0
          
          # 2. Spin up the fresh container (this forces K8s to pull the new image from GHCR)
          kubectl scale deployment react-frontend-deployment --replicas=1